config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'aktuell/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/aktuell/bilder/:id', to: 'aktuell#bilder'

  get '/articles/show/:id', to: 'articles#show'

  get '/articles/gallery/:id', to: 'articles#gallery'

  resources :articles, only: [:show, :index]

  root 'aktuell#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 1 }

    has_many :images

    scope :keywords, -> (term) {where("title LIKE ? OR tags LIKE ? OR text LIKE ?", "%#{term}%", "%#{term}%", "%#{term}%")}

    
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :picture, PictureUploader

    belongs_to :article

    def next
        next_image = article.images.where("id > ?", id).first
        if next_image.nil?
            return article.images.first
        else
            return next_image
        end  
    end
end

app/controllers/aktuell_controller.rb
class AktuellController < ApplicationController
  def index
    @article = Article.last
  end

  def bilder
    @image = Image.find(params[:id])
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.all
        @articles = @articles.keywords(params[:keywords]) if params[:keywords].present?
    end

    def show
        @article = Article.find(params[:id])
    end

    def gallery
        @image = Image.find(params[:id])
    end

end

app/controllers/images_controller.rb
class ImagesController < InheritedResources::Base

  private

    def image_params
      params.require(:image).permit(:title, :description, :picture)
    end
end

app/helpers/aktuell_helper.rb
module AktuellHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/diary_helper.rb
module DiaryHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/aktuell/bilder.html.erb
<div class="images">
    <%= image_tag @image.picture_url, width: '100%' if @image.picture.present? %>
    <a href="/aktuell/bilder/<%= @image.next.id %>" class="main__button" up-target=".images" up-transition="cross-fade">weiter</a>
</div>

app/views/aktuell/index.html.erb
<header class="header">
  <h1 class="header__title">Jonathan Ullherr</h1>
  <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :keywords, params[:keywords], placeholder: "Suche" %>
    
  <% end %>
</header>

<main class="main">
    <aside class="main__link">
        <%= link_to 'alle Wochen', controller: 'articles' %>
    </aside>

    <h2 class="detailansicht__title"><%= @article.title %></h2>

    <div class="detailansicht__img">
        <%= image_tag @article.images.first.picture_url, width: '100%' if @article.images.first.picture.present? %>
    </div>

    <p class="detailansicht__text"><%= @article.text %></p>

    <div class="detailansicht__thumbs">
        <% @article.images.each do |image| %>
            <a href="/aktuell/bilder/<%= image.id -%>" up-modal=".images"><%= image_tag image.picture_url(:thumb) if image.picture.present? %></a>
        <% end %>
    </div>
</main>

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
   
  <% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Zurück', articles_path %>

app/views/articles/gallery.html.erb
<div class="images">
    <%= image_tag @image.picture_url, width: '100%' if @image.picture.present? %>
    <a href="/articles/gallery/<%= @image.next.id %>" class="main__button" up-target=".images" up-transition="cross-fade">weiter</a>
</div>

app/views/articles/index.html.erb
<header class="header">
  <h1 class="header__title">Jonathan Ullherr</h1>
  <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :keywords, params[:keywords], placeholder: "Suche" %>
    
  <% end %>
</header>

<main class="main">
  <aside class="main__link">
    <%= link_to 'aktueller Eintrag', controller: 'aktuell' %>
  </aside>
  <h2 class="main__title">Mein erstes Jahr</h2>
  <ul class="main__overview">
    <% @articles.each do |article| %>
    <li class="overview__item">
      <a href="/articles/show/<%= article.id -%>" class="overview__link"><%= article.abbr %></a>
    </li>
  <% end %>
</ul>

  <% if @articles.blank? %>
    <div class="main__alert">
      <p>Keine Treffer gefunden</p>
    </div>
    <div class="main__button">
      <%= link_to 'Zurück', articles_path %> 
    </div>
  <% end %>
</main>




 

app/views/articles/new.html.erb
<h1>Neuer Eintrag</h1>

<%= render 'form' %>

<%= link_to 'Zurück', articles_path %>

app/views/articles/show.html.erb
<header class="header">
  <h1 class="header__title">Jonathan Ullherr</h1>
  <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :keywords, params[:keywords], placeholder: "Suche" %>
    
  <% end %>
</header>

<main class="main">
    <aside class="main__link">
        <%= link_to 'alle Wochen', controller: 'articles' %>
    </aside>

    <h2 class="detailansicht__title"><%= @article.title %></h2>

    <div class="detailansicht__img">
        <%= image_tag @article.images.first.picture_url, width: '100%' if @article.images.first.picture.present? %>
    </div>

    <div class="detailansicht__text">
        <div class="detailansicht__text--decoration"></div>
        <%= simple_format(@article.text) %>
    </div>

    <div class="detailansicht__thumbs">
        <% @article.images.each do |image| %>
            <a href="/articles/gallery/<%= image.id -%>" up-modal=".images"><%= image_tag image.picture_url(:thumb) if image.picture.present? %></a>
        <% end %>
    </div>
</main>

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.title %></td>
        <td><%= image.description %></td>
        <td><%= image.picture %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @image.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @image.picture %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>